// id: '1a', // Generate random unique ID
// // Get Data from Filename
// title: 'VAS Experience Standup',
// date: '07/11/2023',
// // Extract Info from File Contents
// duration: '30 Minutes',
// speakers: ['Sean', 'David', 'Jason', 'Steven', 'Chris'],
// type: 'Standup',
// plusNumber: 1,

export const MEETINGS = [
  {
    id: '1a',
    title: 'VAS Experience Standup',
    type: 'Standup',
    date: '07/11/2023',
    time: '2:15 PM',
    duration: '30 Minutes',
    attendees: ['Sean', 'David', 'Jason', 'Steven', 'Chris'],
    plusNumber: 1,
  },
  {
    id: '2b',
    title: 'VAS Sprint Planning',
    type: 'Sprint Planning',
    date: '15/11/2023',
    time: '3:00 PM',
    duration: '1 Hour',
    attendees: ['Shaun', 'Daniel', 'Jack', 'Simon', 'Craig'],
    plusNumber: 3,
  },
  {
    id: '3c',
    title: 'Marketing Campaign Review',
    type: 'Review',
    date: '20/11/2023',
    time: '10:30 AM',
    duration: '45 Minutes',
    attendees: ['Emily', 'Sarah', 'Michael', 'Rachel'],
    plusNumber: 2,
  },
  {
    id: '4d',
    title: 'Product Development Meeting',
    type: 'Development',
    date: '25/11/2023',
    time: '11:00 AM',
    duration: '1 Hour 30 Minutes',
    attendees: ['John', 'Emma', 'Liam', 'Olivia'],
    plusNumber: 1,
  },
  {
    id: '5e',
    title: 'Finance Quarterly Review',
    type: 'Review',
    date: '02/12/2023',
    time: '4:00 PM',
    duration: '1 Hour',
    attendees: ['Sophia', 'Noah', 'Ava', 'William', 'Ella'],
    plusNumber: 4,
  },
  {
    id: '6f',
    title: 'Marketing Strategy Workshop',
    type: 'Workshop',
    date: '12/12/2023',
    time: '9:30 AM',
    duration: '2 Hours',
    attendees: ['Hannah', 'Ethan', 'Grace', 'James', 'Nora'],
    plusNumber: 2,
  },
  {
    id: '7g',
    title: 'Customer Support Team Meeting',
    type: 'Team Meeting',
    date: '18/12/2023',
    time: '1:00 PM',
    duration: '45 Minutes',
    attendees: ['Lucas', 'Mia', 'Elijah', 'Chloe'],
    plusNumber: 1,
  },
  {
    id: '8h',
    title: 'Design Sprint Kick-off',
    type: 'Kick-off',
    date: '05/01/2024',
    time: '10:00 AM',
    duration: '1 Hour 15 Minutes',
    attendees: ['Aiden', 'Aria', 'Carter', 'Sofia', 'Liam'],
    plusNumber: 3,
  },
  {
    id: '9i',
    title: 'Project Status Update',
    type: 'Status Update',
    date: '15/01/2024',
    time: '3:30 PM',
    duration: '45 Minutes',
    attendees: ['Zoe', 'Mason', 'Isabella', 'Logan'],
    plusNumber: 2,
  },
  {
    id: '10j',
    title: 'HR Recruitment Meeting',
    type: 'Recruitment',
    date: '22/01/2024',
    time: '11:30 AM',
    duration: '1 Hour 30 Minutes',
    attendees: ['Lily', 'Michael', 'Samantha', 'Evan'],
    plusNumber: 1,
  },
  {
    id: '11k',
    title: 'Sales Strategy Review',
    type: 'Review',
    date: '01/02/2024',
    time: '2:00 PM',
    duration: '1 Hour',
    attendees: ['Mason', 'Abigail', 'Jackson', 'Lily', 'Henry'],
    plusNumber: 4,
  },
  {
    id: '12l',
    title: 'Quality Assurance Meeting',
    type: 'QA',
    date: '10/02/2024',
    time: '4:15 PM',
    duration: '45 Minutes',
    attendees: ['Ella', 'Daniel', 'Ava', 'Matthew'],
    plusNumber: 2,
  },
  {
    id: '13m',
    title: 'Company All-Hands Meeting',
    type: 'All-Hands',
    date: '20/02/2024',
    time: '9:00 AM',
    duration: '1 Hour 30 Minutes',
    attendees: ['Oliver', 'Sophia', 'Jacob', 'Emma'],
    plusNumber: 3,
  },
  {
    id: '14n',
    title: 'IT Infrastructure Planning',
    type: 'Infrastructure',
    date: '02/03/2024',
    time: '2:30 PM',
    duration: '2 Hours',
    attendees: ['William', 'Avery', 'Alexander', 'Grace', 'Ethan'],
    plusNumber: 1,
  },
  {
    id: '15o',
    title: 'Team Building Workshop',
    type: 'Workshop',
    date: '10/03/2024',
    time: '11:00 AM',
    duration: '2 Hours',
    attendees: ['Madison', 'Liam', 'Aria', 'Benjamin', 'Zoe'],
    plusNumber: 2,
  },
];
